import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";
import { Plus_Jakarta_Sans } from "next/font/google";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta",
});

export const metadata = {
  title: "Bennet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      style={{ scrollBehavior: "smooth" }}
      className={plusJakarta.variable}
    >
      <body className="didot">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
